import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#292524',
        'primary-active': '#0c0a09',
        ink: '#0c0a09',
        body: '#4e4e4e',
        'body-strong': '#292524',
        muted: '#777169',
        'muted-soft': '#a8a29e',
        hairline: '#e7e5e4',
        'hairline-soft': '#f0efed',
        'hairline-strong': '#d6d3d1',
        canvas: '#f5f5f5',
        'canvas-soft': '#fafafa',
        'canvas-deep': '#0c0a09',
        'surface-card': '#ffffff',
        'surface-strong': '#f0efed',
        'surface-dark': '#0c0a09',
        'surface-dark-elevated': '#1c1917',
        'on-primary': '#ffffff',
        'on-dark': '#ffffff',
        'on-dark-soft': '#a8a29e',
        'hairline-dark': 'rgba(255,255,255,0.08)',
        'hairline-dark-strong': 'rgba(255,255,255,0.16)',
        gradient: {
          mint: '#a7e5d3',
          peach: '#f4c5a8',
          lavender: '#c8b8e0',
          sky: '#a8c8e8',
          rose: '#e8b8c4',
        },
        success: '#16a34a',
        error: '#dc2626',
        warning: '#b45309',
      },
      fontFamily: {
        display: ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['48px', { lineHeight: '1.08', letterSpacing: '-0.96px', fontWeight: '700' }],
        'display-lg': ['36px', { lineHeight: '1.17', letterSpacing: '-0.36px', fontWeight: '700' }],
        'display-md': ['32px', { lineHeight: '1.13', letterSpacing: '-0.32px', fontWeight: '600' }],
        'display-sm': ['24px', { lineHeight: '1.2', letterSpacing: '-0.1px', fontWeight: '600' }],
        'title-md': ['20px', { lineHeight: '1.35', letterSpacing: '0px', fontWeight: '500' }],
        'title-sm': ['18px', { lineHeight: '1.44', letterSpacing: '0.18px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.5', letterSpacing: '0.16px', fontWeight: '400' }],
        'body-strong': ['16px', { lineHeight: '1.5', letterSpacing: '0.16px', fontWeight: '500' }],
        'body-sm': ['15px', { lineHeight: '1.47', letterSpacing: '0.15px', fontWeight: '400' }],
        caption: ['14px', { lineHeight: '1.5', letterSpacing: '0px', fontWeight: '400' }],
        'caption-upper': ['12px', { lineHeight: '1.4', letterSpacing: '0.96px', fontWeight: '600' }],
        button: ['15px', { lineHeight: '1', letterSpacing: '0px', fontWeight: '500' }],
      },
      borderRadius: {
        xs: '4px',
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        xxl: '24px',
        pill: '9999px',
      },
      spacing: {
        xxs: '4px',
        xs: '8px',
        sm: '12px',
        base: '16px',
        md: '20px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        section: '96px',
      },
      boxShadow: {
        soft: '0 4px 16px rgba(0, 0, 0, 0.04)',
      },
    },
  },
  plugins: [],
} satisfies Config
