import type { Trip } from '../types/trip'

export const seedTrip: Trip = {
  meta: {
    destino: 'África do Sul',
    titulo: 'Gabs & Clara na África do Sul',
    inicio: '2026-08-14',
    fim: '2026-08-28',
    viajantes: ['Gabs', 'Clara'],
    moedaLocal: 'ZAR',
    cambioZARtoBRL: 0.3,
    cambioUSDtoBRL: 5.4,
  },

  itinerario: [
    {
      id: 'd01',
      data: '2026-08-14',
      diaSemana: 'sex',
      base: 'Cidade do Cabo',
      titulo: 'Chegada',
      descricao: 'Desembarque; dia leve; V&A Waterfront.',
      itens: ['Desembarque no aeroporto da Cidade do Cabo', 'Check-in no hotel', 'Passeio leve pelo V&A Waterfront'],
    },
    {
      id: 'd02',
      data: '2026-08-15',
      diaSemana: 'sáb',
      base: 'Cidade do Cabo',
      titulo: 'Cidade',
      descricao: 'Table Mountain, Bo-Kaap, centro.',
      itens: ['Table Mountain (teleférico)', 'Bairro do Bo-Kaap', 'Centro da Cidade do Cabo'],
    },
    {
      id: 'd03',
      data: '2026-08-16',
      diaSemana: 'dom',
      base: 'Cidade do Cabo',
      titulo: 'Península do Cabo',
      descricao: "Chapman's Peak, Cabo da Boa Esperança, pinguins de Boulders.",
      itens: ["Chapman's Peak Drive", 'Cabo da Boa Esperança', 'Pinguins em Boulders Beach'],
    },
    {
      id: 'd04',
      data: '2026-08-17',
      diaSemana: 'seg',
      base: 'Cidade do Cabo',
      titulo: 'Vinho ou adrenalina',
      descricao: 'Winelands (Stellenbosch/Franschhoek) ou cage diving em Gansbaai.',
      itens: ['Opção A: Winelands (Stellenbosch/Franschhoek)', 'Opção B: Cage diving em Gansbaai'],
    },
    {
      id: 'd05',
      data: '2026-08-18',
      diaSemana: 'ter',
      base: 'Garden Route',
      titulo: 'Baleias em Hermanus',
      descricao: 'Carro rumo leste; Hermanus (baleias) → Wilderness.',
      itens: ['Pegar o carro alugado', 'Observação de baleias em Hermanus', 'Seguir até Wilderness'],
    },
    {
      id: 'd06',
      data: '2026-08-19',
      diaSemana: 'qua',
      base: 'Garden Route',
      titulo: 'Knysna',
      descricao: 'Laguna, Knysna Heads, ostras.',
      itens: ['Laguna de Knysna', 'Knysna Heads', 'Ostras frescas'],
    },
    {
      id: 'd07',
      data: '2026-08-20',
      diaSemana: 'qui',
      base: 'Garden Route',
      titulo: 'Tsitsikamma',
      descricao: 'Plettenberg + ponte suspensa; bungee opcional.',
      itens: ['Plettenberg Bay', 'Ponte suspensa de Tsitsikamma', 'Bungee jump (opcional)'],
    },
    {
      id: 'd08',
      data: '2026-08-21',
      diaSemana: 'sex',
      base: 'Trânsito',
      titulo: 'Rumo a Gqeberha',
      descricao: 'Garden Route → Gqeberha (opção Addo). Devolve carro.',
      itens: ['Garden Route → Gqeberha', 'Opção: Addo Elephant Park', 'Devolução do carro alugado'],
    },
    {
      id: 'd09',
      data: '2026-08-22',
      diaSemana: 'sáb',
      base: 'Trânsito',
      titulo: 'Voo p/ Hoedspruit',
      descricao: 'Gqeberha → Joanesburgo → Hoedspruit. Pernoite em Hoedspruit.',
      itens: ['Voo Gqeberha → Joanesburgo', 'Voo Joanesburgo → Hoedspruit', 'Pernoite em Hoedspruit'],
    },
    {
      id: 'd10',
      data: '2026-08-23',
      diaSemana: 'dom',
      base: 'Kruger (Tulani)',
      titulo: 'Check-in + 1º drive',
      descricao: 'Transfer ao Tulani; check-in 14h; game drive ao entardecer.',
      itens: ['Transfer até o Tulani Boutique Lodge', 'Check-in às 14h', 'Game drive ao entardecer'],
      reservado: true,
    },
    {
      id: 'd11',
      data: '2026-08-24',
      diaSemana: 'seg',
      base: 'Kruger (Tulani)',
      titulo: 'Big Five',
      descricao: 'Drives amanhecer e tarde.',
      itens: ['Game drive ao amanhecer', 'Game drive à tarde'],
      reservado: true,
    },
    {
      id: 'd12',
      data: '2026-08-25',
      diaSemana: 'ter',
      base: 'Kruger (Tulani)',
      titulo: 'Imersão no bush',
      descricao: 'Mais drives; última noite na savana.',
      itens: ['Game drives', 'Última noite na savana'],
      reservado: true,
    },
    {
      id: 'd13',
      data: '2026-08-26',
      diaSemana: 'qua',
      base: 'Panorama Route',
      titulo: 'Panorama Route',
      descricao: "Checkout Tulani → Blyde River Canyon, God's Window, Bourke's Luck. Pernoite Graskop/Hazyview.",
      itens: ['Checkout do Tulani', 'Blyde River Canyon', "God's Window", "Bourke's Luck Potholes", 'Pernoite em Graskop/Hazyview'],
    },
    {
      id: 'd14',
      data: '2026-08-27',
      diaSemana: 'qui',
      base: 'Trânsito',
      titulo: 'Rumo a Joanesburgo',
      descricao: 'Panorama Route → Joanesburgo. Pernoite perto do aeroporto.',
      itens: ['Panorama Route → Joanesburgo', 'Pernoite perto do aeroporto'],
    },
    {
      id: 'd15',
      data: '2026-08-28',
      diaSemana: 'sex',
      base: 'Volta',
      titulo: 'Volta ao Brasil',
      descricao: 'Voo Joanesburgo → São Paulo (chega 29).',
      itens: ['Voo Joanesburgo → São Paulo'],
    },
  ],

  reservas: [
    {
      id: 'r01',
      tipo: 'lodge',
      nome: 'Tulani Boutique Lodge',
      status: 'reservado',
      confirmacao: '5002779139',
      checkin: '2026-08-23',
      checkout: '2026-08-26',
      local: 'Grietjie Nature Reserve (Greater Kruger)',
      notas:
        'All-inclusive: 3 refeições/dia + 2 game drives/dia + seleção de bebidas locais. Taxa de conservação ~R100/veículo em dinheiro na saída. Bebidas premium à parte. Aeroporto Hoedspruit (~52 km), transfer da lodge. Hóspede: Gabriel Vaz.',
    },
    {
      id: 'r02',
      tipo: 'voo',
      nome: 'Voo internacional',
      status: 'a_reservar',
      notas: 'GRU → Cidade do Cabo (ida) / Joanesburgo → GRU (volta), open-jaw.',
    },
    {
      id: 'r03',
      tipo: 'voo',
      nome: 'Voo interno',
      status: 'a_reservar',
      notas: 'Gqeberha → Joanesburgo → Hoedspruit (22/08), Airlink.',
    },
    {
      id: 'r04',
      tipo: 'carro',
      nome: 'Carro 1',
      status: 'a_reservar',
      notas: 'Cidade do Cabo → Gqeberha (18–21/08), one-way.',
    },
    {
      id: 'r05',
      tipo: 'carro',
      nome: 'Carro 2',
      status: 'a_reservar',
      notas: 'Hoedspruit → Joanesburgo (26–27/08), Panorama Route.',
    },
    {
      id: 'r06',
      tipo: 'hotel',
      nome: 'Hotel — Cidade do Cabo',
      status: 'a_reservar',
      checkin: '2026-08-14',
      checkout: '2026-08-18',
      notas: '4 noites (14–18/08).',
    },
    {
      id: 'r07',
      tipo: 'hotel',
      nome: 'Hotel — Garden Route',
      status: 'a_reservar',
      notas: 'Wilderness/Knysna/Plett, 3 noites.',
    },
    {
      id: 'r08',
      tipo: 'hotel',
      nome: 'Hotel — Hoedspruit',
      status: 'a_reservar',
      checkin: '2026-08-22',
      checkout: '2026-08-23',
      notas: '1 noite (22/08).',
    },
    {
      id: 'r09',
      tipo: 'hotel',
      nome: 'Hotel — Graskop/Panorama',
      status: 'a_reservar',
      checkin: '2026-08-26',
      checkout: '2026-08-27',
      notas: '1 noite (26/08).',
    },
    {
      id: 'r10',
      tipo: 'hotel',
      nome: 'Hotel — Joanesburgo',
      status: 'a_reservar',
      checkin: '2026-08-27',
      checkout: '2026-08-28',
      notas: '1 noite (27/08).',
    },
  ],

  seguro: {
    seguradora: '',
    apolice: '',
    vigencia: '',
    telefoneEmergencia: '',
    cobertura: '',
    notas: 'Seguro a contratar.',
  },

  checklists: [
    {
      id: 'c01',
      titulo: 'Mala (por clima)',
      grupo: 'mala',
      itens: [
        { id: 'c01-01', texto: 'Kit de frio: fleece/casaco pesado, gorro, luvas, cachecol (game drive do amanhecer é gelado)', feito: false },
        { id: 'c01-02', texto: 'Dias quentes: roupas leves; manga e calça compridas pra manhã', feito: false },
        { id: 'c01-03', texto: 'Cidade do Cabo: corta-vento impermeável; roupa arrumada pra jantar/vinícola', feito: false },
        { id: 'c01-04', texto: 'Bush: roupas em tons de terra (cáqui/verde/bege); evitar azul-escuro, preto e branco', feito: false },
        { id: 'c01-05', texto: 'Sapato fechado confortável', feito: false },
        { id: 'c01-06', texto: 'Protetor solar, óculos escuros, chapéu, repelente', feito: false },
        { id: 'c01-07', texto: 'Adaptador de tomada (tipo M/N)', feito: false },
        { id: 'c01-08', texto: 'Carregador/power bank; câmera/binóculos', feito: false },
      ],
    },
    {
      id: 'c02',
      titulo: 'Reservas (to-do)',
      grupo: 'reservas',
      itens: [
        { id: 'c02-01', texto: 'Safári — Tulani (23–26/08)', feito: true },
        { id: 'c02-02', texto: 'Vacina de febre amarela (10 dias antes)', feito: false },
        { id: 'c02-03', texto: 'Voos internacionais (open-jaw)', feito: false },
        { id: 'c02-04', texto: 'Voos internos (Gqeberha→JNB→Hoedspruit)', feito: false },
        { id: 'c02-05', texto: 'Carro Cidade do Cabo→Gqeberha', feito: false },
        { id: 'c02-06', texto: 'Carro Hoedspruit→Joanesburgo', feito: false },
        { id: 'c02-07', texto: 'Hotéis (Cidade do Cabo, Garden Route, Hoedspruit, Graskop, Joburg)', feito: false },
        { id: 'c02-08', texto: 'Seguro viagem', feito: false },
        { id: 'c02-09', texto: 'Passeios (baleias Hermanus, Tsitsikamma)', feito: false },
      ],
    },
    {
      id: 'c03',
      titulo: 'Documentos',
      grupo: 'documentos',
      itens: [
        { id: 'c03-01', texto: 'Passaporte válido (6+ meses)', feito: false },
        { id: 'c03-02', texto: 'Certificado de febre amarela (físico)', feito: false },
        { id: 'c03-03', texto: 'Habilitação internacional (PID)', feito: false },
        { id: 'c03-04', texto: 'Cópias/foto dos documentos no celular', feito: false },
      ],
    },
  ],

  gastos: [],

  dicas: [
    {
      id: 't01',
      categoria: 'Clima/Mala',
      titulo: 'Inverno na África do Sul',
      texto: 'Manhãs/noites frias, tardes quentes. Vista em camadas. Game drive do amanhecer é gelado.',
    },
    {
      id: 't02',
      categoria: 'Saúde',
      titulo: 'Febre amarela e malária',
      texto: 'Febre amarela obrigatória (10 dias antes). Kruger/Grietjie é área de malária — falar com médico sobre profilaxia.',
    },
    {
      id: 't03',
      categoria: 'Safári',
      titulo: 'Cores e roupas no bush',
      texto: 'Cores de terra; evitar azul-escuro/preto (tsé-tsé) e branco (poeira). Manga e calça de manhã.',
    },
    {
      id: 't04',
      categoria: 'Direção',
      titulo: 'Mão inglesa e tomadas',
      texto: 'Mão inglesa (esquerda). Tomadas M/N. PID recomendada.',
    },
    {
      id: 't05',
      categoria: 'Dinheiro',
      titulo: 'Cartão, gorjetas e taxas',
      texto: 'Cartão aceito em quase tudo. Gorjeta 10–15%; no safári, gratificar guia e tracker. Levar algum cash para taxas (ex.: conservação Grietjie).',
    },
  ],
}
